Feature/create intake subsystem
246overclocked/2022-Robot-Code-Java pull request #27
Opened 2022-01-24 02:32 UTC by kchenturtles

2022-01-24 03:26 UTC, aidan-mundy requested changes
Pretty good. A few changes to make to get everything sorted for merging

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void setIntakeSpeed(double intakeSpeed) {
Change to setSpinSpeed

IntakeSpeed is a bit redundant

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +    if (solenoid.get() == DoubleSolenoid.Value.kReverse && intakeSpeed != 0) {
add `isExtended`, `isRetracted` and `isNeutralExtension` methods that return booleans

Then use `isRetracted` here

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +   * Toggles the {@link DoubleSolenoid.Value} between Forward and Reverse. If in neutral toggles it
Change terminology from "Forward" and "Reverse" to "Extended" and "Retracted"

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void retract() {
```suggestion
  public void setRetracted() {
```

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +   * Sets the intake DoubleSolenoid to Reverse.
```suggestion
   * Retracts the intake and sets spin speed to 0.
```

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void neutral() {
```suggestion
  public void setNeutralExtension() {
```

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +   * Sets the intake DoubleSolenoid to neutral.
```suggestion
   * Sets the intake to Neutral extension.
```

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +   * Sets the intake DoubleSolenoid to Forward.
```suggestion
   * Extends the intake.
```

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void extend() {
```suggestion
  public void setExtended() {
```

2022-01-24 03:26 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public Intake(int intakeMotorID, int forwardChannel, int reverseChannel) {
Please add another constructor that allows for a configurable MotorType

2022-01-24 15:43 UTC, chit-sudeep approved these changes, later dismissed
Review intake review code and javadocs.

Looks good!

2022-01-25 01:49 UTC, aidan-mundy requested changes
Thanks for the updated code! Just one last change that I didn't notice before...

2022-01-25 01:49 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  public void setSpinSpeed(double intakeSpeed) {
Change "intakeSpeed" to "speed" or "newSpeed"

The method declaration should include a "throws" like this
```java
public void setSpinSpeed(double newSpeed) throws IllegalStateException {
```

Also, the javadoc should include a properly formatted "@throws" declaration

2022-01-25 02:48 UTC, chit-sudeep approved these changes, later dismissed
Looked over all code and javadocs and if Aidan's suggestions were fixed.

Looks good!

2022-01-25 03:07 UTC, aidan-mundy requested changes

2022-01-25 03:07 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
>     * @param intakeSpeed The speed of the intake motor
Changes to input variables should be reflected in the javadocs
```suggestion
   * @param newSpeed The speed of the intake motor
```

2022-01-25 04:07 UTC, chit-sudeep approved these changes
Looked over all of the code, especially the Javadocs.

Looks good!

2022-01-26 01:04 UTC, aidan-mundy approved these changes

2022-01-26 01:04 UTC, merged