Add Primary and Secondary Driver Joysticks
246overclocked/2022-Robot-Code-Java pull request #36
Opened 2022-01-26 17:20 UTC by kchenturtles

Added Primary and Secondary Driver Joysticks to RobotContainer.
Added inner class to Constants called IOConstants with variables that store the port for each joystick

Closes #35

2022-01-27 05:51 UTC, aidan-mundy requested changes

2022-01-27 05:51 UTC, aidan-mundy commented on src/main/java/frc/robot/Constants.java
> +   * The IOConstants class stores the port number of the Primary Driver {@link Joystick} and the
Change to
```
   * Stores constants related to driver controls, SmartDashboard and other IO (Input/Output).
```

2022-01-28 03:11 UTC, ch33zZz approved these changes
javaDoc has been replaced, looks good!

2022-01-28 04:10 UTC, aidan-mundy approved these changes

2022-01-28 04:10 UTC, merged