made RunTowerCommand & StopTowerCommand commands + added javaDoc
246overclocked/2022-Robot-Code-Java pull request #37
Opened 2022-01-28 02:54 UTC by ch33zZz

Created RuntowerCommand and StopTowerCommand

closes#22

2022-01-28 04:09 UTC, aidan-mundy submitted a review, later dismissed

2022-01-28 12:20 UTC, citrus-melon requested changes

2022-01-28 12:20 UTC, citrus-melon commented on src/main/java/frc/robot/commands/tower/StopTowerCommand.java
> +   * @param tower the {@link tower} to stop
Capitalize the link target:


```suggestion
   * @param tower the {@link Tower} to stop
```

2022-01-29 04:26 UTC, aidan-mundy approved these changes

2022-01-29 12:53 UTC, citrus-melon approved these changes

2022-01-30 05:42 UTC, merged