Add extra tower motors
246overclocked/2022-Robot-Code-Java pull request #54
Opened 2022-02-03 13:38 UTC by kchenturtles

Reconfigured for four motors: top left, bottom left, top right, bottom right. Right side motors spin in opposite direction to left side motors.

Closes #45

2022-02-03 20:29 UTC, aidan-mundy requested changes
Looks mostly fine. Need to update the constructor call in RobotContainer to match the new constructor format.

2022-02-03 23:35 UTC, aidan-mundy submitted a review, later dismissed
Fixed a bunch of merge conflicts, but looks good now.

2022-02-03 23:52 UTC, aidan-mundy approved these changes

2022-02-04 01:23 UTC, citrus-melon approved these changes

2022-02-04 01:24 UTC, merged