Feature/change drive base to falcon
246overclocked/2022-Robot-Code-Java pull request #64
Opened 2022-02-06 01:29 UTC by kchenturtles

Replaced CanSparkMax motors with TalonFX, used NeutralMode instead of IdleMode (added constant to keep track of motor neutral mode). Had to cast TalonFX to MotorController for DifferentialDrive -- was thinking about if we could make back motors follow front instead?

2022-02-06 15:29 UTC, aidan-mundy requested changes
Casting a TalonFX to a MotorController doesn't really work. Create the motors as a WPI_TalonFX instead. 

The initialization method you've created uses motor.set. the set() method on CTRE devices is like setSpeed. In this case, the DRIVEVASE_MOTORS_DEMAND is a nonsense value (currently set to 1) that would cause the motor to start spinning on initialization. This should not be there. For this subsystem, the DifferentialDrive group handles setting the speed. 

 Also, instead of calling setNeutralMode on the motors directly and manually setting the motorNeutralMode variable, you can just call the setBrakingMode method. This makes the initializeDriveMotor method obsolete.

2022-02-06 18:13 UTC, kchenturtles commented
So do you not need to set the control mode for the motors?

2022-02-06 22:00 UTC, chit-sudeep approved these changes
Reviewed all changes. Didn't find any mistakes.

Looks good!

2022-02-09 03:13 UTC, aidan-mundy approved these changes

2022-02-09 03:13 UTC, merged