Change Intake to use Victor SPX
246overclocked/2022-Robot-Code-Java pull request #66
Opened 2022-02-06 18:27 UTC by kchenturtles

Changed IdleMode to NeutralMode, deleted CANSparkMax, etc.

Closes #63

2022-02-06 21:58 UTC, chit-sudeep approved these changes
Reviewed all changes.

Looks good!

2022-02-06 22:09 UTC, chit-sudeep requested changes
Fix javadoc

2022-02-06 22:09 UTC, chit-sudeep commented on src/main/java/frc/robot/subsystems/Intake.java
> +   * Constructs an Intake with a {@link VictorSPX} with the given CAN ID and a
Remove “CAN ID”

2022-02-06 22:12 UTC, chit-sudeep approved these changes
Sorry for the confusion; just learned that VictorSPXs have a CAN ID.

2022-02-09 03:16 UTC, aidan-mundy approved these changes

2022-02-09 03:16 UTC, merged