Change Intake Motor to TalonFX and set current limits for all subsystems
246overclocked/2022-Robot-Code-Java pull request #68
Opened 2022-02-10 14:07 UTC by chit-sudeep

Change Intake Motor to TalonFX and set current limits for all subsystems.
Also creates a new subclass in Constants.java for Drive Constants.
See Constants.java for the thresholds.

Closes #65 .

2022-02-10 17:34 UTC, aidan-mundy requested changes

2022-02-10 17:34 UTC, aidan-mundy commented on src/main/java/frc/robot/subsystems/Intake.java
> +  private final WPI_TalonFX intakeMotor;
Intake should be WPI_TalonSRX

2022-02-15 01:06 UTC, kchenturtles approved these changes
Reviewed changes. Looks ok.

2022-02-15 01:09 UTC, aidan-mundy approved these changes

2022-02-15 01:09 UTC, merged