Use Generic HID
246overclocked/2022-Robot-Code-Java pull request #71
Opened 2022-02-24 11:36 UTC by chit-sudeep

Closes #70 

Use Generic HID instead of joystick

* Gets rid of Joystick import
* Gets rid of Xbox controller import
* Still uses joystick button

2022-02-24 12:00 UTC, citrus-melon requested changes

2022-02-24 12:00 UTC, citrus-melon commented on src/main/java/frc/robot/RobotContainer.java
> +   * ({@link edu.wpi.first.wpilibj.Joystick} or {@link edu.wpi.first.wpilibj.GenericHID} or
GenericHID isn't a subclass of GenericHID

2022-02-24 12:08 UTC, citrus-melon approved these changes

2022-03-08 17:46 UTC, aidan-mundy approved these changes

2022-03-08 17:46 UTC, merged